---

- name: create CA folders
  file: 
    state=directory
    path={{ item }}
    mode=0755
  with_items:
      - "{{ sslcert_folder }}/CA"
      - "{{ sslcert_folder }}/CA/certs"
      - "{{ sslcert_folder }}/CA/crl"

- name: create CA private folder
  file:
    state=directory
    path={{ sslcert_folder }}/CA/private
    mode=0700

- stat:
    path={{ sslcert_folder }}/CA/index.txt
  register: index_file

- name: touch index db file
  file:
    state=touch
    path={{ sslcert_folder }}/CA/index.txt
    mode=0755
  when: index_file.stat.exists == false

- name: config opensslCA.cnf
  template:
    src={{ item }}.j2
    dest={{ sslcert_folder }}/CA/{{ item }}
    mode=666
  with_items:
    - opensslCA.cnf

- stat: path={{ sslcert_folder }}/CA/private/selfsignCA.key
  register: key_file

- name: create CA private key
  shell: openssl genrsa -out selfsignCA.key 2048
  args:
    chdir: "{{ sslcert_folder }}/CA/private"
  when: key_file.stat.exists == false

- stat: path="{{ sslcert_folder }}/CA/selfsignCA.pem"
  register: cert_file

- name: create CA Cert
  shell: openssl req -x509 -new -sha256 -extensions v3_ca -config opensslCA.cnf -key private/selfsignCA.key -days 3650 -out selfsignCA.pem
  args:
    chdir: "{{ sslcert_folder }}/CA"
  when: cert_file.stat.exists == false

