---
# tasks file for selfsign
#
- name: create working folder
  file: 
    state=directory
    path={{ item }}
    mode=0755
  with_items:
      - "{{ selfsign_folder }}"

- name: create CA
  include: createCA.yml

- name: create cert and key
  include: createCert.yml

- name: set owner
  include: owner.yml

