---

- name: set owner
  file:
    state=file
    path={{ sslcert_folder }}/{{ item }}
    owner={{ sslcert_owner }}
  with_items:
    - certs/{{ sslcert_next_cert_name }}.crt
    - private/{{ sslcert_next_cert_name }}.key
